### ISSUE TITLE
[Feature Request] Configuration

### ISSUE THREAD

**Issue by tedstriker** [jakubburkiewicz/node-red-contrib-ollama#10]
Hi there,
nice node for ollama you've created. Thank you.
If possible, it would also be nice to have a configuration, instead passing all these information with every message sent.
Having the url, a pre-selected model and maybe a prompt where a placeholder could be added for a property of the processed message.

**Comment by jakubburkiewicz** [comment]
@tedstriker 
Thank you for the kind words.
Please check version 0.3.0. You should find the improvements you requested there.
