### ISSUE TITLE
Why the requirement for Ollama to be installed on the same system?

### ISSUE THREAD

**Issue by mecworks** [jakubburkiewicz/node-red-contrib-ollama#4]
In our office, we have a single Ollama server with large GPU power and all clients connect to it using the web API.  Why is there a requirement for having Ollama installed on the same machine for this plugin to work?  Many times, NodeRed is installed on a Raspberry Pis which are incapable of running Ollama and should be able to connect to a remote Ollama instance.

**Comment by jakubburkiewicz** [comment]
Hi @mecworks 
There is no requirement to use the Ollama instance on the same device/system.

In version 0.1.7, I introduced support for the host field, where you can specify which server the node should communicate with.

Doesn't this solve your problem?

**Comment by mecworks** [comment]
It does however, the documentation is out of date.  It still says "Also you need to install the Ollama on the same system." in the README.  The documentation is out of date both here in Github and in the module that's installable from within NodeRed.

**Comment by jakubburkiewicz** [comment]
I've updated the information in the README.md file.
