### ISSUE TITLE
[Feature Request] Add API Key Ability

### ISSUE THREAD

**Issue by iotemylabs** [jakubburkiewicz/node-red-contrib-ollama#5]
Hi, first of all, great work!

In the Ollama server instance I have, I require the use of an API Key for each request in the header. In the documentation of this node, I don't see the ability to add an API Key for every call, could this be updated as a setting in a future release?

Thank you!

**Comment by jakubburkiewicz** [comment]
Hi @iotemylabs 

Thank you for your kind words :)

First of all, could you let me know if sending an API Key is actually supported by Ollama.js (and Ollama itself), and I just forgot to implement it?
Or maybe you have a custom Ollama setup that supports receiving API Keys?
Alternatively, are you perhaps referring to a completely independent server that accepts requests and then forwards them to Ollama?

If it's the first case, please point me to where in the Ollama/Ollama.js documentation the API Key parameter is mentioned, and I'll be happy to correct my oversight as soon as possible.

The other two cases would fall outside the scope of this project.
The goal of this project is to stick strictly to the functionality provided by Ollama.js without going beyond what this library offers.

Of course, that doesn't mean I don't want to help. Maybe it’s just a matter of creating a new project that builds upon this one but adds the functionality needed for your specific use case.
