### ISSUE TITLE
[Feature Request] tool calling

### ISSUE THREAD

**Issue by freakontrol** [jakubburkiewicz/node-red-contrib-ollama#6]
Hi, i really like this project, I was just wondering if the [tool calling](https://ollama.com/blog/tool-support)
 is supported?

**Comment by jakubburkiewicz** [comment]
Hi @freakontrol 
Thank you :)
I'll add it on the first weekend of October.

**Comment by jakubburkiewicz** [comment]
@freakontrol
I just released version 0.2.0, which among other things, supports the `tools` parameter in the `ollama-chat` node.
Have fun!

**Comment by freakontrol** [comment]
I'll try it soon. Thank you very much!
