### ISSUE TITLE
Nor URL?

### ISSUE THREAD

**Issue by whitelex** [jakubburkiewicz/node-red-contrib-ollama#7]
So how do I put the url, model etc? Where are the settings?

**Comment by NeoCortex3** [comment]
![image](https://github.com/user-attachments/assets/bb1907e8-d37a-48f2-8422-4984228b9d4e)

![image](https://github.com/user-attachments/assets/f06542da-7393-40cc-8d23-6f4e6216424a)

![image](https://github.com/user-attachments/assets/5e9e6d39-d84b-4aed-b72a-0c36b2623ca0)

**Comment by bakman2** [comment]
@NeoCortex3  thanks for creating this node - i used ollamajs in a function node, which acted in a similar way as your nodes. To make it 'somewhat' easier for the user, I think it would help if you made use of a config to set the host, which then could be selected in the nodes.

**Comment by NeoCortex3** [comment]
@bakman2 you got that wrong, I didn't create this node. @jakubburkiewicz is the creator of this.
I just posted the screenshots to show @whitelex how to use it.

To implement the idea of a config, please talk to @jakubburkiewicz or fork this repo and programm it yourself.

Best regards,
Julix

**Comment by jakubburkiewicz** [comment]
@NeoCortex3, Thank you for the clarification.

@bakman2, Please refer to the documentation available for each node after installing the plugin in Node-RED. It took me a lot of time to prepare it.
I hope you understand that explaining individual aspects to everyone now, which are already documented, doesn’t make much sense.
If after reading the documentation you still feel that something is wrong or missing, write a detailed description.
It's possible that while writing it, you'll come up with a solution to your problem (this often happens to me).

**Comment by bakman2** [comment]
@jakubburkiewicz i think you misunderstood my feedback. I understand how your nodes work. 
My point was that `msg.payload.host` will always be required in order to use your nodes, this is what [config nodes](https://nodered.org/docs/creating-nodes/config-nodes) could be used for, to make it common among your nodes, but i digress.

**Comment by jakubburkiewicz** [comment]
@bakman2, You should have said what you meant from the start :)

Indeed, adding a configuration node is a good idea. I think I’ll be able to take care of it in the last week of this month.

P.S. To be honest, your first response sounds like you couldn't be bothered to look up the documentation and expect free advice with minimal effort. I didn’t quite understand what you meant from your second response.

**Comment by jakubburkiewicz** [comment]
@bakman2 I'm really sorry. Now I see that the first message isn't from you :)

**Comment by jakubburkiewicz** [comment]
@whitelex , @NeoCortex3 , @bakman2
I think the changes introduced in version 0.3.0 will appeal to you. Have fun! (Sorry for the long wait.)

**Comment by bakman2** [comment]
@jakubburkiewicz thanks a lot for the updates, i cannot make it work, but that is probably on myself.
Is it correct that the `keepalive` accepts a string as input ?

**Comment by jakubburkiewicz** [comment]
Hi @bakman2 
Yes. `keepalive` accepts string or integer. Default value is `5m` (five minutes)
If in doubt, check https://github.com/ollama/ollama-js?tab=readme-ov-file#api or https://github.com/ollama/ollama/blob/main/docs/api.md.
I won't be smarter than those sources ;)

**Comment by dattazigzag** [comment]
> ![image](https://github.com/user-attachments/assets/bb1907e8-d37a-48f2-8422-4984228b9d4e)
> 
> ![image](https://github.com/user-attachments/assets/f06542da-7393-40cc-8d23-6f4e6216424a)
> 
> ![image](https://github.com/user-attachments/assets/5e9e6d39-d84b-4aed-b72a-0c36b2623ca0)


----

Hey guys for me this doens't work: any clues, how to debug? 
Issue described here: https://github.com/jakubburkiewicz/node-red-contrib-ollama/issues/20
